export const SHOES_LIST_REQUEST = "SHOES_LIST_REQUEST";
export const SHOES_LIST_SUCCESS = "SHOES_LIST_SUCCESS";
export const SHOES_LIST_FAIL = "SHOES_LIST_FAIL";

export const MOBILES_LIST_REQUEST = "MOBILES_LIST_REQUEST";
export const MOBILES_LIST_SUCCESS = "MOBILES_LIST_SUCCESS";
export const MOBILES_LIST_FAIL = "MOBILES_LIST_FAIL";

export const MANCLOTHES_LIST_REQUEST = "MANCLOTHES_LIST_REQUEST";
export const MANCLOTHES_LIST_SUCCESS = "MANCLOTHES_LIST_SUCCESS";
export const MANCLOTHES_LIST_FAIL = "MANCLOTHES_LIST_FAIL";

export const TOYS_LIST_REQUEST = "TOYS_LIST_REQUEST";
export const TOYS_LIST_SUCCESS = "TOYS_LIST_SUCCESS";
export const TOYS_LIST_FAIL = "TOYS_LIST_FAIL";

export const BABYMOM_LIST_REQUEST = "BABYMOM_LIST_REQUEST";
export const BABYMOM_LIST_SUCCESS = "BABYMOM_LIST_SUCCESS";
export const BABYMOM_LIST_FAIL = "BABYMOM_LIST_FAIL";

export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";


export const PRODUCT_GET_ALL_REQUEST = "PRODUCT_GET_ALL_REQUEST";
export const PRODUCT_GET_ALL_SUCCESS = "PRODUCT_GET_ALL_SUCCESS";
export const PRODUCT_GET_ALL_FAIL = "PRODUCT_GET_ALL_FAIL";

export const PRODUCT_SINGLE_DETAIL_REQUEST = "PRODUCT_SINGLE_DETAIL_REQUEST";
export const PRODUCT_SINGLE_DETAIL_SUCCESS = "PRODUCT_SINGLE_DETAIL_SUCCESS";
export const PRODUCT_SINGLE_DETAIL_FAIL = "PRODUCT_SINGLE_DETAIL_FAIL";

export const PRODUCT_CREATE_REVIEW_REQUEST = "PRODUCT_CREATE_REVIEW_REQUEST";
export const PRODUCT_CREATE_REVIEW_SUCCESS = "PRODUCT_CREATE_REVIEW_SUCCESS";
export const PRODUCT_CREATE_REVIEW_FAIL = "PRODUCT_CREATE_REVIEW_FAIL";
export const PRODUCT_CREATE_REVIEW_RESET = "PRODUCT_CREATE_REVIEW_RESET";

export const PRODUCT_LIST_CATEGORY_REQUEST = "PRODUCT_LIST_CATEGORY_REQUEST";
export const PRODUCT_LIST_CATEGORY_SUCCESS = "PRODUCT_LIST_CATEGORY_SUCCESS";
export const PRODUCT_LIST_CATEGORY_FAIL = "PRODUCT_LIST_CATEGORY_FAIL";

export const NEWS_LIST_REQUEST = "NEWS_LIST_REQUEST";
export const NEWS_LIST_SUCCESS = "NEWS_LIST_SUCCESS";
export const NEWS_LIST_FAIL = "NEWS_LIST_FAIL";

export const NEW_SINGLE_DETAIL_REQUEST = "NEW_SINGLE_DETAIL_REQUEST";
export const NEW_SINGLE_DETAIL_SUCCESS = "NEW_SINGLE_DETAIL_SUCCESS";
export const NEW_SINGLE_DETAIL_FAIL = "NEW_SINGLE_DETAIL_FAIL";


