export const VOUCHER_GET_ALL_OF_USER_REQUEST = "VOUCHER_GET_ALL_OF_USER_REQUEST";
export const VOUCHER_GET_ALL_OF_USER_SUCCESS = "VOUCHER_GET_ALL_OF_USER_SUCCESS";
export const VOUCHER_GET_ALL_OF_USER_FAIL = "VOUCHER_GET_ALL_OF_USER_FAIL";
export const VOUCHER_GET_ALL_OF_USER_RESET = "VOUCHER_GET_ALL_OF_USER_RESET";
