export const ORDER_LIST_REQUEST = "ORDER_LIST_REQUEST";
export const ORDER_LIST_SUCCESS = "ORDER_LIST_SUCCESS";
export const ORDER_LIST_FAIL = "ORDER_LIST_FAIL";

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL";

export const ORDER_MARK_DELIVERED_REQUEST = "ORDER_MARK_DELIVERED_REQUEST";
export const ORDER_MARK_DELIVERED_SUCCESS = "ORDER_MARK_DELIVERED_SUCCESS";
export const ORDER_MARK_DELIVERED_FAIL = "ORDER_MARK_DELIVERED_FAIL";
export const ORDER_MARK_DELIVERED_RESET = "ORDER_MARK_DELIVERED_RESET";

export const ORDER_MARK_CONFIRMED_REQUEST = "ORDER_MARK_CONFIRMED_REQUEST";
export const ORDER_MARK_CONFIRMED_SUCCESS = "ORDER_MARK_CONFIRMED_SUCCESS";
export const ORDER_MARK_CONFIRMED_FAIL = "ORDER_MARK_CONFIRMED_FAIL";
export const ORDER_MARK_CONFIRMED_RESET = "ORDER_MARK_CONFIRMED_RESET";

export const ORDER_ADMIN_GET_ORDERS_OF_USER_REQUEST = "ORDER_ADMIN_GET_ORDERS_OF_USER_REQUEST";
export const ORDER_ADMIN_GET_ORDERS_OF_USER_SUCCESS = "ORDER_ADMIN_GET_ORDERS_OF_USER_SUCCESS";
export const ORDER_ADMIN_GET_ORDERS_OF_USER_FAIL = "ORDER_ADMIN_GET_ORDERS_OF_USER_FAIL";
export const ORDER_ADMIN_GET_ORDERS_OF_USER_RESET = "ORDER_ADMIN_GET_ORDERS_OF_USER_RESET";