export const PRODUCT_GETALL_ADMIN_REQUEST = "PRODUCT_GETALL_ADMIN_REQUEST";
export const PRODUCT_GETALL_ADMIN_SUCCESS = "PRODUCT_GETALL_ADMIN_SUCCESS";
export const PRODUCT_GETALL_ADMIN_FAIL = "PRODUCT_GETALL_ADMIN_FAIL";

export const PRODUCT_LIST_CATEGORY_REQUEST = "PRODUCT_LIST_CATEGORY_REQUEST";
export const PRODUCT_LIST_CATEGORY_SUCCESS = "PRODUCT_LIST_CATEGORY_SUCCESS";
export const PRODUCT_LIST_CATEGORY_FAIL = "PRODUCT_LIST_CATEGORY_FAIL";

export const PRODUCT_DELETE_REQUEST = "PRODUCT_DELETE_REQUEST";
export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS";
export const PRODUCT_DELETE_FAIL = "PRODUCT_DELETE_FAIL";
export const PRODUCT_DELETE_RESET = "PRODUCT_DELETE_RESET";

export const PRODUCT_CREATE_REQUEST = "PRODUCT_CREATE_REQUEST";
export const PRODUCT_CREATE_SUCCESS = "PRODUCT_CREATE_SUCCESS";
export const PRODUCT_CREATE_FAIL = "PRODUCT_CREATE_FAIL";
export const PRODUCT_CREATE_RESET = "PRODUCT_CREATE_RESET";

export const PRODUCT_EDIT_REQUEST = "PRODUCT_EDIT_REQUEST";
export const PRODUCT_EDIT_SUCCESS = "PRODUCT_EDIT_SUCCESS";
export const PRODUCT_EDIT_FAIL = "PRODUCT_EDIT_FAIL";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

export const PRODUCT_UPDATE_REQUEST = "PRODUCT_UPDATE_REQUEST";
export const PRODUCT_UPDATE_SUCCESS = "PRODUCT_UPDATE_SUCCESS";
export const PRODUCT_UPDATE_FAIL = "PRODUCT_UPDATE_FAIL";
export const PRODUCT_UPDATE_RESET = "PRODUCT_UPDATE_RESET";

export const PRODUCT_ADMIN_GET_CATEGORY_REQUEST = "PRODUCT_ADMIN_GET_CATEGORY_REQUEST";
export const PRODUCT_ADMIN_GET_CATEGORY_SUCCESS = "PRODUCT_ADMIN_GET_CATEGORY_SUCCESS";
export const PRODUCT_ADMIN_GET_CATEGORY_FAIL = "PRODUCT_ADMIN_GET_CATEGORY_FAIL";
export const PRODUCT_ADMIN_GET_CATEGORY_RESET = "PRODUCT_ADMIN_GET_CATEGORY_RESET";

export const PRODUCT_ADMIN_EDIT_CATEGORY_REQUEST = "PRODUCT_ADMIN_EDIT_CATEGORY_REQUEST";
export const PRODUCT_ADMIN_EDIT_CATEGORY_SUCCESS = "PRODUCT_ADMIN_EDIT_CATEGORY_SUCCESS";
export const PRODUCT_ADMIN_EDIT_CATEGORY_FAIL = "PRODUCT_ADMIN_EDIT_CATEGORY_FAIL";
export const PRODUCT_ADMIN_EDIT_CATEGORY_RESET = "PRODUCT_ADMIN_EDIT_CATEGORY_RESET";

export const PRODUCT_ADMIN_DELETE_CATEGORY_REQUEST = "PRODUCT_ADMIN_DELETE_CATEGORY_REQUEST";
export const PRODUCT_ADMIN_DELETE_CATEGORY_SUCCESS = "PRODUCT_ADMIN_DELETE_CATEGORY_SUCCESS";
export const PRODUCT_ADMIN_DELETE_CATEGORY_FAIL = "PRODUCT_ADMIN_DELETE_CATEGORY_FAIL";
export const PRODUCT_ADMIN_DELETE_CATEGORY_RESET = "PRODUCT_ADMIN_DELETE_CATEGORY_RESET";

export const PRODUCT_ADMIN_ADD_CATEGORY_REQUEST = "PRODUCT_ADMIN_ADD_CATEGORY_REQUEST";
export const PRODUCT_ADMIN_ADD_CATEGORY_SUCCESS = "PRODUCT_ADMIN_ADD_CATEGORY_SUCCESS";
export const PRODUCT_ADMIN_ADD_CATEGORY_FAIL = "PRODUCT_ADMIN_ADD_CATEGORY_FAIL";
export const PRODUCT_ADMIN_ADD_CATEGORY_RESET = "PRODUCT_ADMIN_ADD_CATEGORY_RESET";

export const PRODUCT_ADMIN_GET_ALL_NEWS_REQUEST = "PRODUCT_ADMIN_GET_ALL_NEWS_REQUEST";
export const PRODUCT_ADMIN_GET_ALL_NEWS_SUCCESS = "PRODUCT_ADMIN_GET_ALL_NEWS_SUCCESS";
export const PRODUCT_ADMIN_GET_ALL_NEWS_FAIL = "PRODUCT_ADMIN_GET_ALL_NEWS_FAIL";
export const PRODUCT_ADMIN_GET_ALL_NEWS_RESET = "PRODUCT_ADMIN_GET_ALL_NEWS_RESET";

export const PRODUCT_ADMIN_ADD_NEWS_REQUEST = "PRODUCT_ADMIN_ADD_NEWS_REQUEST";
export const PRODUCT_ADMIN_ADD_NEWS_SUCCESS = "PRODUCT_ADMIN_ADD_NEWS_SUCCESS";
export const PRODUCT_ADMIN_ADD_NEWS_FAIL = "PRODUCT_ADMIN_ADD_NEWS_FAIL";
export const PRODUCT_ADMIN_ADD_NEWS_RESET = "PRODUCT_ADMIN_ADD_NEWS_RESET";

export const PRODUCT_ADMIN_DELETE_NEWS_REQUEST = "PRODUCT_ADMIN_DELETE_NEWS_REQUEST";
export const PRODUCT_ADMIN_DELETE_NEWS_SUCCESS = "PRODUCT_ADMIN_DELETE_NEWS_SUCCESS";
export const PRODUCT_ADMIN_DELETE_NEWS_FAIL = "PRODUCT_ADMIN_DELETE_NEWS_FAIL";
export const PRODUCT_ADMIN_DELETE_NEWS_RESET = "PRODUCT_ADMIN_DELETE_NEWS_RESET";

export const NEW_SINGLE_DETAIL_REQUEST = "NEW_SINGLE_DETAIL_REQUEST";
export const NEW_SINGLE_DETAIL_SUCCESS = "NEW_SINGLE_DETAIL_SUCCESS";
export const NEW_SINGLE_DETAIL_FAIL = "NEW_SINGLE_DETAIL_FAIL";
