export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_LIST_REQUEST = "USER_LIST_REQUEST";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_FAIL = "USER_LIST_FAIL";
export const USER_LIST_RESET = "USER_LIST_RESET";

export const USER_BLOCKED_REQUEST = "USER_BLOCKED_REQUEST";
export const USER_BLOCKED_SUCCESS = "USER_BLOCKED_SUCCESS";
export const USER_BLOCKED_FAIL = "USER_BLOCKED_FAIL";
export const USER_BLOCKED_RESET = "USER_BLOCKED_RESET";

export const USER_UNBLOCKED_REQUEST = "USER_UNBLOCKED_REQUEST";
export const USER_UNBLOCKED_SUCCESS = "USER_UNBLOCKED_SUCCESS";
export const USER_UNBLOCKED_FAIL = "USER_UNBLOCKED_FAIL";
export const USER_UNBLOCKED_RESET = "USER_UNBLOCKED_RESET";

export const USER_ADMIN_GET_USER_REQUEST = "USER_ADMIN_GET_USER_REQUEST";
export const USER_ADMIN_GET_USER_SUCCESS = "USER_ADMIN_GET_USER_SUCCESS";
export const USER_ADMIN_GET_USER_FAIL = "USER_ADMIN_GET_USER_FAIL";
export const USER_ADMIN_GET_USER_RESET = "USER_ADMIN_GET_USER_RESET";

export const USER_ADMIN_EDIT_USER_REQUEST = "USER_ADMIN_EDIT_USER_REQUEST";
export const USER_ADMIN_EDIT_USER_SUCCESS = "USER_ADMIN_EDIT_USER_SUCCESS";
export const USER_ADMIN_EDIT_USER_FAIL = "USER_ADMIN_EDIT_USER_FAIL";
export const USER_ADMIN_EDIT_USER_RESET = "USER_ADMIN_EDIT_USER_RESET";

export const USER_ADMIN_DELETE_USER_REQUEST = "USER_ADMIN_DELETE_USER_REQUEST";
export const USER_ADMIN_DELETE_USER_SUCCESS = "USER_ADMIN_DELETE_USER_SUCCESS";
export const USER_ADMIN_DELETE_USER_FAIL = "USER_ADMIN_DELETE_USER_FAIL";
export const USER_ADMIN_DELETE_USER_RESET = "USER_ADMIN_DELETE_USER_RESET";

export const USER_ADMIN_ADD_USER_REQUEST = "USER_ADMIN_ADD_USER_REQUEST";
export const USER_ADMIN_ADD_USER_SUCCESS = "USER_ADMIN_ADD_USER_SUCCESS";
export const USER_ADMIN_ADD_USER_FAIL = "USER_ADMIN_ADD_USER_FAIL";
export const USER_ADMIN_ADD_USER_RESET = "USER_ADMIN_ADD_USER_RESET";

// export const ADMIN_DETAILS_REQUEST = "ADMIN_DETAILS_REQUEST";
// export const ADMIN_DETAILS_SUCCESS = "ADMIN_DETAILS_SUCCESS";
// export const ADMIN_DETAILS_FAIL = "ADMIN_DETAILS_FAIL";
// export const ADMIN_DETAILS_RESET = "ADMIN_DETAILS_RESET";

export const ADMIN_UPDATE_PROFILE_REQUEST = "ADMIN_DETAILS_REQUEST";
export const ADMIN_UPDATE_PROFILE_SUCCESS = "ADMIN_DETAILS_SUCCESS";
export const ADMIN_UPDATE_PROFILE_FAIL = "ADMIN_DETAILS_FAIL";
export const ADMIN_UPDATE_PROFILE_RESET = "ADMIN_DETAILS_RESET";

