export const VOUCHER_ADMIN_GET_ALL_REQUEST = "VOUCHER_ADMIN_GET_ALL_REQUEST";
export const VOUCHER_ADMIN_GET_ALL_SUCCESS = "VOUCHER_ADMIN_GET_ALL_SUCCESS";
export const VOUCHER_ADMIN_GET_ALL_FAIL = "VOUCHER_ADMIN_GET_ALL_FAIL";
export const VOUCHER_ADMIN_GET_ALL_RESET = "VOUCHER_ADMIN_GET_ALL_RESET";

export const VOUCHER_SINGLE_DETAIL_REQUEST = "VOUCHER_SINGLE_DETAIL_REQUEST";
export const VOUCHER_SINGLE_DETAIL_SUCCESS = "VOUCHER_SINGLE_DETAIL_SUCCESS";
export const VOUCHER_SINGLE_DETAIL_FAIL = "VOUCHER_SINGLE_DETAIL_FAIL";

export const VOUCHER_SINGLE_UPDATE_REQUEST = "VOUCHER_SINGLE_UPDATE_REQUEST";
export const VOUCHER_SINGLE_UPDATE_SUCCESS = "VOUCHER_SINGLE_UPDATE_SUCCESS";
export const VOUCHER_SINGLE_UPDATE_FAIL = "VOUCHER_SINGLE_UPDATE_FAIL";
export const VOUCHER_SINGLE_UPDATE_RESET = "VOUCHER_SINGLE_UPDATE_RESET";

export const VOUCHER_SINGLE_CREATE_REQUEST = "VOUCHER_SINGLE_CREATE_REQUEST";
export const VOUCHER_SINGLE_CREATE_SUCCESS = "VOUCHER_SINGLE_CREATE_SUCCESS";
export const VOUCHER_SINGLE_CREATE_FAIL = "VOUCHER_SINGLE_CREATE_FAIL";
export const VOUCHER_SINGLE_CREATE_RESET = "VOUCHER_SINGLE_CREATE_RESET";

export const VOUCHER_SINGLE_DELETE_REQUEST = "VOUCHER_SINGLE_DELETE_REQUEST";
export const VOUCHER_SINGLE_DELETE_SUCCESS = "VOUCHER_SINGLE_DELETE_SUCCESS";
export const VOUCHER_SINGLE_DELETE_FAIL = "VOUCHER_SINGLE_DELETE_FAIL";
export const VOUCHER_SINGLE_DELETE_RESET = "VOUCHER_SINGLE_DELETE_RESET";